### ISSUE TITLE
Would you mind releasing a compiled image?

### ISSUE THREAD

**Issue by thomasplus** [Pranav-Talmale/device_xiaomi_psyche-ofox#1]
Hi @Pranav-Talmale, thanks for your hard work. I would like to ask if this repo is currently available? Could you post a compiled image if possible?

Also, I would like to ask how should I build the device tree from scratch? I found a lot of articles online but they all seem a bit outdated, do you have any articles to recommend? thank you!

**Comment by Pranav-Talmale** [comment]
The tree is still a WiP.
I am focusing on different projects for now. The repo is buildable but the device bootloops on the ofox splash. On top of that mtp is dead so there is little to no hope of debugging. I also don't have the device in hand. Maybe you can continue to develope the tree.
You can contact me on telegram if you need assistance. I would love to help you. My telegram id : @raphael_alpha
